### ISSUE TITLE
Make the portal ID a link that opens in Atom

### ISSUE THREAD

**Issue by johndbritton** [atom/teletype#109]
I think it’d be worth creating and implementing a file opening handler for an atom portal scheme.

This way when you share a portal ID it would be clickable and it would open with atom automatically.

`atom-portal://portal-is-here`

---

**UPDATE 2018-03-19**: We'll likely tackle this via a series of pull requests, with each one addressing one or more of the items below:

- [x] Teach Teletype to join portal via URL (https://github.com/atom/teletype/pull/346)
    - Add URI handler
    - Automatically join the portal when URL is followed
    - Add command for getting the URL
    - Don't provide any UI for getting the URL. (We'll handle that below.)
- [ ] Ask the user to confirm before joining the portal [[motivation](https://github.com/atom/teletype/blob/e35483b1fa69c3ef1ef56f0c437000d4dcda934b/doc/rfcs/003-quickly-collaborate-with-coworkers-and-friends.md#join-a-portal-via-url)]
    - Provide option to join
    - Provide option to decline/ignore
    - Provide option to automatically join when following future portal URLs
    - Provide configuration setting to enable/disable this option
- [x] Update Teletype popover UI to provide portal URL to host (#348)
- [x] Update Teletype popover UI to allow guest to enter portal URL to join portal [[motivation](https://github.com/atom/teletype/pull/344#discussion_r175438235)] (#348)
- [x] Gracefully handle edge cases (#348)
    - [x] If user enters a raw portal ID or a malformed URL in the "join portal" dialog, look for a GUID and try to use it as the portal ID
    - [x] If a malformed URL is passed to Teletype's URI handler (e.g., `atom://teletype/whoops`), show error message (e.g., "No portal exists with that URL")
    - [x] Update "No portal exists with that ID" message to speak in terms of URLs instead of IDs

**Comment by Arcanemagus** [comment]
In addition to the references in #33, note that Atom core has URI support now: https://github.com/atom/atom/pull/15935.

**Comment by BinaryMuse** [comment]
For infos:

Relevant PR: https://github.com/atom/atom/pull/11399
Docs: http://flight-manual.atom.io/hacking-atom/sections/handling-uris/

**Comment by nathansobo** [comment]
Looks like this will be doable once 1.23 hits stable thanks to @BinaryMuse and I think it should be high on our list.

**Comment by jasonrudolph** [comment]
We're digging into this starting this week. I've updated the issue body to serve as a tracking issue as we implement the various aspects of this functionality.

**Comment by jasonrudolph** [comment]
Collectively, #346, #348, and #350 bring support for sharing and joining a portal via URL. These improvements will go out in the next release of the package.

**Comment by jasonrudolph** [comment]
> These improvements will go out in the next release of the package.

Teletype 0.11.0 is out with support for [sharing and joining a portal via URL](https://blog.atom.io/2018/03/29/new-in-teletype-faster-setup-and-improved-multi-file-support.html#joining-a-portal-is-as-easy-as-clicking-a-link).
