### ISSUE TITLE
Require authentication for (almost) all real-time-server endpoints

### ISSUE THREAD

**Issue by jasonrudolph** [atom/teletype#123]
### TODO

Require authentication with a valid GitHub OAuth token for almost all [endpoints](https://github.com/atom/real-time-server/blob/cb31c9ad932a32dc28428ddb1f0752902ed79ede/lib/controller-layer.js):

- [x] `GET /identity`
- [x] `POST /peers/:id/signals`
- [x] `GET /ice-servers`
- [x] `GET /portals/:id`
- [x] `POST /portals`

We won't require authentication for:

- `GET /protocol-version`
- `GET _/ping`
- `GET /boomtown`

### Context

From the security review in https://github.com/github/appsec-reviews/issues/157#issuecomment-336600390:

>> I'm also curious about when the application chooses to check the user identity. In `real-time-client` the [`createPortal()`](https://github.com/atom/real-time-client/blob/master/lib/real-time-client.js#L86) method calls `verifyOAuthToken` which hits the `/identity` endpoint then continues with the `/portals` request. This feels like client-side protection for creating a portal. I don't think there is much risk in letting users create a portal w/o an OAuth token but if we're going to require it at some point it makes sense to just require it on the `/portals` route [as noted in this comment](https://github.com/atom/real-time-client/blob/master/lib/real-time-client.js#L84). Also of note, these token shouldn't require any scopes so we limit exposure if they get leaked somewhere.
>>
>> [...]
>>
>> Can we authenticate our ICE servers? Seems like anyone could use them. Low risk but a minor abuse vector.
>
> Thanks for pointing this out. Given the limited number of endpoints that we currently expose, we will update the code to require authentication for every request. Notably, this not only helps with security and abuse prevention, but it may also help measure user growth and retention.
