### ISSUE TITLE
Popover UI/UX Enhancements

### ISSUE THREAD

**Issue by jasonrudolph** [atom/teletype#124]
We've talked about a handful of potential UI/UX enhancements in Slack, but I think we'd benefit from capturing them all in one spot. Let's use this as a tracking issue.

#### No active portals

<img width="299" alt="screen shot 2017-10-23 at 3 28 00 pm" src="https://user-images.githubusercontent.com/2988/31909032-cfea3eaa-b806-11e7-8f51-9dfb5f83b784.png">

#### After clicking "Join a Portal"

<img width="301" alt="screen shot 2017-10-23 at 3 28 09 pm" src="https://user-images.githubusercontent.com/2988/31909033-d001f784-b806-11e7-9fa0-4f0a9cc09d00.png">

#### Active host portal and multiple active guest portals

<img width="302" alt="screenshot" src="https://user-images.githubusercontent.com/2988/31908720-d0aee72e-b805-11e7-9b84-9220eeec082a.png">

### TODO

- [x] Make all the "copy", "leave", and "join" buttons the same size.
- [x] Use the same font for the host portal ID (at the top) and the guest portal ID at the bottom.
- [x] Add a border separating the "Join Portal" section from the sections above, as shown in the mockup in https://github.com/atom/real-time/pull/114#issuecomment-337688689.
- [x] Show spinner (or other indication of work in progress) when enabling sharing. (Currently, if it takes you a while to receive the response from the server, you can be left wondering whether anything is happening. [[demo](https://user-images.githubusercontent.com/2988/31909301-a5376c2c-b807-11e7-8feb-069c1f2a333c.gif)]) (https://github.com/atom/real-time/pull/126)
- ~~Provide affordance for clicking on a guest portal in the popover to navigate to that portal's tab~~
