### ISSUE TITLE
Improve tethering UI

### ISSUE THREAD

**Issue by as-cii** [atom/teletype#155]
Instead of showing people's avatars only when they are offscreen, we should always show everyone's avatar instead, like in the picture below:

![untitled](https://user-images.githubusercontent.com/482957/32115499-57bc7706-bb47-11e7-8a91-a3d387e87397.jpg)

As you can notice, the person you are following will be indicated with a little chain icon (or some other kind of indicator). Clicking on an avatar will follow/unfollow the corresponding person.

In case the user moves their cursor behind an avatar, we will move the whole cluster of avatars (top, middle or bottom) it belongs to all the way to the left (without moving the other two clusters).

### TODO

- [x] Always show everyone's avatar (https://github.com/atom/real-time/pull/161)
- [x] Show the link icon next to the person that you are explicitly following, not the person that you are implicitly following
- [ ] Prevent the avatar from covering up the cursor/selection
