### ISSUE TITLE
Identify Portal Participants

### ISSUE THREAD

**Issue by jasonrudolph** [atom/teletype#40]
For the very first step on the road to authentication and presence [1] \[2], we'll enhance the package to identify all participants in the portal.

## Behavior

This initial staff-ship will provide the following behavior:

- [x] As a user, when I attempt to share or join a portal, and the real-time package does not yet have a GitHub OAuth token for me, the package prompts me to obtain a token and paste that token into Atom (#87)
- [x] As a host, when a guest joins my portal, I see a notification saying, "@`<guest-username>` has joined your portal" [3] (#87)
- [ ] As a guest, when I join a portal, I see a notification saying, "You're now collaborating with @`<host-username>`" [3]
- [x] As a guest, when another guest joins the portal, I see a notification saying, "@`<guest-username>` has joined the portal" [3]

## TODO

This is a partial task list, largely intended to help me keep track of things going on across various repositories :smile:. We'll know that everything is actually done when the package provides the behavior described above. ☝️

- [x] Add OAuth flow to atom.io for real-time package (https://github.com/github/atom.io/pull/1183)
- [x] Add "happy path" authentication logic to real-time-server (https://github.com/atom/real-time-server/pull/4)
- ~~End-to-end happy path with real-time package reading OAuth token from env var~~
- [x] Store/fetch OAuth token to/from keytar
- [x] Address all TODO comments introduced in https://github.com/atom/real-time-server/pull/4
- [x] Integrate authentication into real-time-client 
- [x] Handle failure cases in real-time package
    - [x] OAuth token not valid
    - [x] GitHub API rate limit exceeded
    - [x] GitHub API inaccessible
- [x] Add DNS entry for tachyon.atom.io (https://github.com/github/dns/pull/722)
- [x] Add CI for real-time-server, now that it has tests (https://github.com/atom/real-time-server/pull/5)

---

[1] [Portals roadmap](https://github.com/github/atom-log/blob/057f37c/real-time-collaboration/portals-roadmap.md#milestone-4-authentication-and-presence-universe-stretch-goal)
[2] [Buddy list exploration](https://github.com/atom/real-time/issues/22)
[3] We'll likely tweak the copy before shipping :sparkles:
